---
apiVersion: batch/v1
kind: Job
metadata:
  name: [PROJECT]-satd-[NO]
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
      - name: td-worker
        image: s141015/review_td:v1
        imagePullPolicy: Always
        resources:
          requests:
            memory: "[MEMORY]"
            cpu: "[CPU]"
        volumeMounts:
          - name: smb
            mountPath: "/data"
            readOnly: false
        command: ["sh", "[FILE]", "[PROJECT]", "[START]", "[STOP]", "[WORKER]"]
      volumes:
        - name: smb
          persistentVolumeClaim:
            claimName: pvc-smb
      restartPolicy: Never